//! CD-TEXT encoding.
//!
//! Pure: no COM, no I/O, no platform types. Everything here is verifiable
//! without a drive, which matters because the alternative way to find a bug in
//! this format is a coaster.
//!
//! What CD-TEXT is, physically: 18-byte *packs* carried in the R-W subchannel
//! of the disc's **lead-in**. Four packs fill one sector's 96 subchannel
//! symbols exactly (4 × 18 bytes = 72 bytes = 96 six-bit symbols), with no
//! interleaving and no parity beyond each pack's own CRC.
//!
//! Layout verified against the libcdio CD-TEXT format reference and cdrdao's
//! encoder. Both are read as protocol documentation; no code was copied, since
//! cdrdao is GPL-2.0 and this tree is GPL-3.0-or-later.

mod crc;
mod encode;

pub use encode::{encode_packs, CdTextError, PACK_BYTES};

/// Does this 18-byte pack carry a correct CRC?
///
/// Used when reading CD-TEXT back off a burned disc: a drive that claims the
/// capability and writes zeros scores nothing here instead of looking like a
/// success.
pub fn pack_crc_matches(pack: &[u8]) -> bool {
    pack.len() >= PACK_BYTES && crc::pack_crc(&pack[..16]) == [pack[16], pack[17]]
}

/// EBU language code. English is what a Subsonic library labels itself in
/// practice; the block structure allows eight, and shipping one is deliberate
/// (see the feature README).
pub const LANGUAGE_ENGLISH: u8 = 0x09;

/// Character code for ISO-8859-1, the only set worth defaulting to: it is what
/// every CD-TEXT-capable player understands.
pub const CHARSET_ISO_8859_1: u8 = 0x00;

/// Subchannel symbols in one sector.
pub const SUBCHANNEL_BYTES_PER_SECTOR: usize = 96;

/// Packs carried by one sector's R-W subchannel.
pub const PACKS_PER_SECTOR: usize = 4;

/// Subchannel bytes one pack spans: 18 bytes at six bits per byte is 24
/// symbols. Four of these fill a sector's 96 bytes.
pub const PACK_SLOT_BYTES: usize = 24;

/// One track's CD-TEXT strings.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CdTextTrack {
    pub title: String,
    pub performer: String,
}

/// Everything that goes into a disc's CD-TEXT block.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CdTextInput {
    pub disc_title: String,
    pub disc_performer: String,
    pub tracks: Vec<CdTextTrack>,
}

/// An encoded CD-TEXT block, ready for the lead-in.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CdTextBlock {
    packs: Vec<[u8; PACK_BYTES]>,
}

impl CdTextBlock {
    pub(crate) fn new(packs: Vec<[u8; PACK_BYTES]>) -> Self {
        Self { packs }
    }

    /// Encode `input` into a single English, ISO-8859-1 block.
    pub fn encode(input: &CdTextInput) -> Result<Self, CdTextError> {
        encode_packs(input).map(Self::new)
    }

    pub fn packs(&self) -> &[[u8; PACK_BYTES]] {
        &self.packs
    }

    pub fn pack_count(&self) -> usize {
        self.packs.len()
    }

    pub fn is_empty(&self) -> bool {
        self.packs.is_empty()
    }

    /// Sectors of lead-in this block needs, at four packs per sector.
    pub fn sector_count(&self) -> usize {
        self.packs.len().div_ceil(PACKS_PER_SECTOR)
    }

    /// Render the block as lead-in subchannel bytes, one 96-byte group per
    /// sector.
    ///
    /// The packs are laid end to end — four per sector, 72 bytes — and then
    /// spread six bits to a byte across the R-W channels, MSB first. P and Q
    /// are left clear: the drive generates both from the cue sheet.
    ///
    /// This is the `41h` DATA FORM shape: raw P-W from the host, main channel
    /// generated by the drive.
    pub fn to_subchannel(&self) -> Vec<u8> {
        let mut out = vec![0_u8; self.sector_count() * SUBCHANNEL_BYTES_PER_SECTOR];
        for (index, pack) in self.packs.iter().enumerate() {
            let base = index * PACK_SLOT_BYTES;
            for (symbol_index, symbol) in six_bit_symbols(pack).enumerate() {
                out[base + symbol_index] = symbol;
            }
        }
        out
    }
}

/// Split 18 bytes into the 24 six-bit symbols the R-W channels carry, MSB
/// first.
fn six_bit_symbols(pack: &[u8; PACK_BYTES]) -> impl Iterator<Item = u8> + '_ {
    (0..24).map(move |symbol_index| {
        let bit_offset = symbol_index * 6;
        let mut symbol = 0_u8;
        for bit in 0..6 {
            let absolute = bit_offset + bit;
            let byte = pack[absolute / 8];
            let value = (byte >> (7 - (absolute % 8))) & 1;
            symbol = (symbol << 1) | value;
        }
        symbol
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> CdTextInput {
        CdTextInput {
            disc_title: "Long Way Round".into(),
            disc_performer: "Various Artists".into(),
            tracks: vec![
                CdTextTrack { title: "Kolibri".into(), performer: "Ansel Mora".into() },
                CdTextTrack { title: "Static Bloom".into(), performer: "The Faraday Cage".into() },
            ],
        }
    }

    #[test]
    fn read_back_verification_accepts_our_own_packs() {
        let block = CdTextBlock::encode(&sample()).expect("encodes");
        for pack in block.packs() {
            assert!(pack_crc_matches(pack));
        }
    }

    #[test]
    fn read_back_verification_rejects_zeros_and_corruption() {
        assert!(!pack_crc_matches(&[0u8; PACK_BYTES]));
        assert!(!pack_crc_matches(&[0u8; 4]), "a short buffer is not a pack");

        let block = CdTextBlock::encode(&sample()).expect("encodes");
        let mut damaged = block.packs()[0];
        damaged[6] ^= 0x01;
        assert!(!pack_crc_matches(&damaged));
    }

    #[test]
    fn four_pack_slots_fill_a_sector_exactly() {
        assert_eq!(PACKS_PER_SECTOR * PACK_SLOT_BYTES, SUBCHANNEL_BYTES_PER_SECTOR);
    }

    #[test]
    fn six_bit_symbols_are_msb_first_and_cover_every_bit() {
        let mut pack = [0u8; PACK_BYTES];
        pack[0] = 0b1111_1100; // first symbol all ones, next two bits zero
        let symbols: Vec<u8> = six_bit_symbols(&pack).collect();
        assert_eq!(symbols.len(), 24);
        assert_eq!(symbols[0], 0b111111);
        assert_eq!(symbols[1] & 0b110000, 0);
    }

    #[test]
    fn every_symbol_fits_in_six_bits() {
        let block = CdTextBlock::encode(&sample()).expect("encodes");
        for byte in block.to_subchannel() {
            assert_eq!(byte & 0b1100_0000, 0, "P/Q bits must stay clear for the drive");
        }
    }

    #[test]
    fn subchannel_is_a_whole_number_of_sectors() {
        let block = CdTextBlock::encode(&sample()).expect("encodes");
        let sub = block.to_subchannel();
        assert_eq!(sub.len() % SUBCHANNEL_BYTES_PER_SECTOR, 0);
        assert_eq!(sub.len() / SUBCHANNEL_BYTES_PER_SECTOR, block.sector_count());
    }

    #[test]
    fn four_packs_fill_exactly_one_sector() {
        // The property the whole lead-in layout rests on.
        assert_eq!(PACKS_PER_SECTOR * PACK_BYTES * 8 / 6, SUBCHANNEL_BYTES_PER_SECTOR);
    }

    #[test]
    fn a_partial_final_sector_is_padded_not_truncated() {
        let block = CdTextBlock::encode(&sample()).expect("encodes");
        // Sample is far from a multiple of four packs; the buffer must still be
        // sector-aligned rather than cut short.
        let expected = block.pack_count().div_ceil(PACKS_PER_SECTOR);
        assert_eq!(block.sector_count(), expected);
        assert_eq!(block.to_subchannel().len(), expected * SUBCHANNEL_BYTES_PER_SECTOR);
    }

    #[test]
    fn symbols_round_trip_back_to_the_original_pack_bytes() {
        let block = CdTextBlock::encode(&sample()).expect("encodes");
        let sub = block.to_subchannel();

        for (index, pack) in block.packs().iter().enumerate() {
            let sector = index / PACKS_PER_SECTOR;
            let slot = index % PACKS_PER_SECTOR;
            let base = sector * SUBCHANNEL_BYTES_PER_SECTOR + slot * 24;

            // Reassemble 24 six-bit symbols back into 18 bytes.
            let mut bits = Vec::with_capacity(144);
            for symbol in &sub[base..base + 24] {
                for bit in (0..6).rev() {
                    bits.push((symbol >> bit) & 1);
                }
            }
            let mut rebuilt = [0u8; PACK_BYTES];
            for (i, chunk) in bits.as_chunks::<8>().0.iter().enumerate() {
                rebuilt[i] = chunk.iter().fold(0u8, |acc, b| (acc << 1) | b);
            }
            assert_eq!(&rebuilt, pack, "pack {index} did not survive the R-W mapping");
        }
    }
}
