//! Session-At-Once writing with a CD-TEXT lead-in (Windows).
//!
//! IMAPI2 has no CD-TEXT support, so this path drives the recorder itself
//! through `IDiscRecorder2Ex::SendCommand*` — still inside IMAPI2, so it runs
//! unelevated and keeps IMAPI2's exclusive-access handling.
//!
//! Confirmed working against real hardware. The three things that had to be
//! right, and were not obvious:
//!
//! 1. The lead-in DATA FORM is `41h` — raw P-W from the host, main channel
//!    generated by the drive.
//! 2. The lead-in is **the whole lead-in**, from the disc's ATIP start (around
//!    97 minutes, so ~13 500 sectors) up to the pregap at −150, with the pack
//!    sequence repeated to fill it. Writing only enough sectors to hold the
//!    packs once produces a disc whose CD-TEXT cannot be read back.
//! 3. The cue sheet's lead-in entry carries the disc's real lead-in start,
//!    read from `READ DISC INFORMATION`, not zero.
//!
//! **The whole design turns on one boundary.** Everything up to and including
//! `SEND CUE SHEET` is negotiation: if the drive refuses any of it, nothing has
//! touched the disc and the caller falls back to the IMAPI2 path that is known
//! to work. From the first `WRITE(10)` onwards the session is being burned and
//! there is no way back. `SaoError` names which side of that line a failure
//! happened on, and the caller must respect it.

use std::fs::File;
use std::io::Read;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use tauri::AppHandle;
use windows::Win32::Storage::Imapi::{
    IDiscRecorder2, IDiscRecorder2Ex, IMAPI_MODE_PAGE_REQUEST_TYPE_CURRENT_VALUES,
    IMAPI_MODE_PAGE_TYPE_WRITE_PARAMETERS,
};
use windows::Win32::System::Com::CoTaskMemFree;
use windows_core::Interface;

use crate::cdtext::{CdTextBlock, SUBCHANNEL_BYTES_PER_SECTOR};
use crate::job::{emit_progress, PROGRESS_THROTTLE_MS};
use crate::mmc::cue::{build_cue_sheet, CueTrack, Msf};
use crate::mmc::mode::{self, WriteParameters};
use crate::mmc::{
    lead_in_sectors, lead_in_start_lba, read_disc_information_cdb, send_cue_sheet_cdb,
    write_10_cdb,
};
use crate::model::{BurnPhase, CdTextVerification, BYTES_PER_AUDIO_SECTOR};
use crate::render::RenderedTrack;

/// Bytes in one Red Book audio sector as the cue sheet's DATA FORM `00h`
/// describes it: 2352 of main data, subcode generated by the drive.
const MAIN_BYTES: usize = BYTES_PER_AUDIO_SECTOR;

/// Sectors per `WRITE(10)`. 27 × 2352 is just under 64 KB, which every drive
/// accepts; the real limit is queried and this is only the cap.
const DEFAULT_CHUNK_SECTORS: usize = 27;

/// Command timeouts, in seconds.
const TIMEOUT_SETUP: u32 = 30;
const TIMEOUT_WRITE: u32 = 300;

/// Which side of the point of no return a failure happened on.
#[derive(Debug)]
pub enum SaoError {
    /// The drive refused the setup. Nothing was written; falling back to the
    /// IMAPI2 path is safe and the disc is untouched.
    Setup(String),
    /// The burn had already begun. The disc is spoiled; do not retry onto it.
    Write(String),
}

impl std::fmt::Display for SaoError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SaoError::Setup(message) | SaoError::Write(message) => write!(f, "{message}"),
        }
    }
}

/// Decode a fixed-format sense buffer into something a person can act on.
fn sense_text(sense: &[u8; 18]) -> String {
    let key = sense[2] & 0x0F;
    let asc = sense[12];
    let ascq = sense[13];
    let meaning = match (key, asc, ascq) {
        (0x05, 0x24, _) => "the drive rejected a field in the command",
        (0x05, 0x26, _) => "the drive rejected a parameter value",
        (0x05, 0x20, _) => "the drive does not support that command",
        (0x02, 0x3A, _) => "there is no disc in the drive",
        (0x03, 0x0C, _) => "a write error on the disc",
        (0x04, _, _) => "a hardware fault in the drive",
        (0x0B, 0x08, _) => "the drive lost its data stream (buffer underrun)",
        _ => "the drive reported an error",
    };
    format!("{meaning} (sense {key:X}/{asc:02X}/{ascq:02X})")
}

/// Feeds the program area 2352-byte sectors, track after track.
struct SectorSource {
    files: Vec<File>,
    current: usize,
}

impl SectorSource {
    fn open(tracks: &[RenderedTrack]) -> Result<Self, String> {
        let files = tracks
            .iter()
            .map(|track| {
                File::open(&track.path)
                    .map_err(|e| format!("cannot read {}: {e}", track.path.display()))
            })
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Self { files, current: 0 })
    }

    /// Fill `buffer` with whole sectors, returning how many bytes were read.
    ///
    /// Rendering already padded every track to a sector boundary, so a short
    /// read means one file ended and the next track continues the disc.
    fn read(&mut self, buffer: &mut [u8]) -> Result<usize, String> {
        let mut filled = 0;
        while filled < buffer.len() && self.current < self.files.len() {
            let read = self.files[self.current]
                .read(&mut buffer[filled..])
                .map_err(|e| format!("reading rendered audio failed: {e}"))?;
            if read == 0 {
                self.current += 1;
            } else {
                filled += read;
            }
        }
        Ok(filled)
    }
}

/// Write the whole session, optionally with a CD-TEXT lead-in.
///
/// Returns the number of program-area sectors written.
#[allow(clippy::too_many_arguments)] // One write; bundling would only move the arity.
pub fn write_session(
    app: &AppHandle,
    job_id: &str,
    recorder: &IDiscRecorder2,
    tracks: &[RenderedTrack],
    cd_text: Option<&CdTextBlock>,
    catalog: Option<&str>,
    test_write: bool,
    buffer_underrun_free: bool,
    cancel: &Arc<AtomicBool>,
) -> Result<u32, SaoError> {
    let ex = recorder
        .cast::<IDiscRecorder2Ex>()
        .map_err(|e| SaoError::Setup(format!("this drive exposes no command interface: {e}")))?;

    // ── Negotiation. Nothing below writes to the disc. ───────────────────
    configure_write_parameters(&ex, cd_text.is_some(), test_write, buffer_underrun_free)?;

    // ISRC rides in the cue sheet on this path — the IMAPI2 path sets it via
    // IRawCDImageTrackInfo, and for a while this one silently dropped it.
    let cue_tracks: Vec<CueTrack> = tracks
        .iter()
        .map(|track| CueTrack { sectors: track.sectors, isrc: track.isrc.clone() })
        .collect();
    // The lead-in geometry has to be known before the cue sheet, which
    // announces where the lead-in starts.
    let lead_in = match cd_text {
        Some(_) => Some(read_lead_in(&ex)?),
        None => None,
    };
    let sheet = build_cue_sheet(&cue_tracks, lead_in.as_ref().map(|l| l.start), catalog);
    send_cue_sheet(&ex, &sheet)?;

    if cancel.load(Ordering::Relaxed) {
        return Err(SaoError::Setup("cancelled".to_string()));
    }

    // ── Past this line the laser is on. ──────────────────────────────────
    let sectors_total: u32 = tracks.iter().map(|track| track.sectors).sum();
    let chunk_sectors = max_chunk_sectors(&ex);

    if let (Some(block), Some(lead_in)) = (cd_text, lead_in.as_ref()) {
        write_cd_text_lead_in(&ex, block, lead_in, chunk_sectors)?;
    }

    let written = write_program_area(
        app,
        job_id,
        &ex,
        tracks,
        sectors_total,
        chunk_sectors,
        cancel,
    )?;

    synchronize_cache(&ex)?;
    Ok(written)
}

/// Read the Write Parameters page, edit it, and hand it back.
fn configure_write_parameters(
    ex: &IDiscRecorder2Ex,
    cd_text: bool,
    test_write: bool,
    buffer_underrun_free: bool,
) -> Result<(), SaoError> {
    let mut data: *mut u8 = std::ptr::null_mut();
    let mut size: u32 = 0;

    // SAFETY: IMAPI2 allocates the page with the COM allocator; freed below.
    let read = unsafe {
        ex.GetModePage(
            IMAPI_MODE_PAGE_TYPE_WRITE_PARAMETERS,
            IMAPI_MODE_PAGE_REQUEST_TYPE_CURRENT_VALUES,
            &raw mut data,
            &raw mut size,
        )
    };

    let page = if read.is_ok() && !data.is_null() && size > 0 {
        // SAFETY: IMAPI2 reported `size` valid bytes at `data`.
        unsafe { std::slice::from_raw_parts(data, size as usize) }.to_vec()
    } else {
        Vec::new()
    };
    if !data.is_null() {
        // SAFETY: allocated by IMAPI2 with the COM task allocator.
        unsafe { CoTaskMemFree(Some(data.cast())) };
    }

    if page.is_empty() {
        return Err(SaoError::Setup(
            "the drive would not report its write settings".to_string(),
        ));
    }

    let edited = mode::apply(
        &page,
        WriteParameters { test_write, buffer_underrun_free, raw_subchannel: cd_text },
    )
    .map_err(|e| SaoError::Setup(e.to_string()))?;

    // SAFETY: `edited` is the drive's own page with a few fields changed.
    unsafe { ex.SetModePage(IMAPI_MODE_PAGE_REQUEST_TYPE_CURRENT_VALUES, &edited) }.map_err(
        |e| {
            SaoError::Setup(format!(
                "the drive rejected Session-At-Once settings, so CD-TEXT is not possible on it: {e}"
            ))
        },
    )
}

fn send_cue_sheet(ex: &IDiscRecorder2Ex, sheet: &[u8]) -> Result<(), SaoError> {
    let cdb = send_cue_sheet_cdb(sheet.len() as u32);
    let mut sense = [0_u8; 18];
    // SAFETY: cdb and sheet outlive the call; sense is written by the drive.
    unsafe { ex.SendCommandSendDataToDevice(&cdb, &mut sense, TIMEOUT_SETUP, sheet) }.map_err(
        |e| {
            SaoError::Setup(format!(
                "the drive rejected the disc layout: {} ({e})",
                sense_text(&sense)
            ))
        },
    )
}

/// Sectors per write, clamped to what the drive will accept.
///
/// Sized against the audio sector, which is the larger of the two block sizes
/// in play, so the same figure is safe for the 96-byte lead-in blocks too.
fn max_chunk_sectors(ex: &IDiscRecorder2Ex) -> usize {
    // SAFETY: a plain property read on the recorder.
    let limit = unsafe { ex.GetMaximumNonPageAlignedTransferSize() }.unwrap_or(0) as usize;
    if limit == 0 {
        return DEFAULT_CHUNK_SECTORS;
    }
    (limit / MAIN_BYTES).clamp(1, DEFAULT_CHUNK_SECTORS)
}

/// Where this disc's lead-in begins, and how long it is.
///
/// Read from `READ DISC INFORMATION` (bytes 17-19 hold the lead-in start as
/// MSF). Both numbers matter: the cue sheet announces the start, and the write
/// has to cover the whole extent.
struct LeadIn {
    start: Msf,
    sectors: u32,
}

fn read_lead_in(ex: &IDiscRecorder2Ex) -> Result<LeadIn, SaoError> {
    let mut buffer = [0_u8; 34];
    let cdb = read_disc_information_cdb(buffer.len() as u16);
    let mut sense = [0_u8; 18];
    let mut fetched: u32 = 0;

    // SAFETY: a read of at most `buffer.len()` bytes into our own buffer.
    unsafe {
        ex.SendCommandGetDataFromDevice(
            &cdb,
            &mut sense,
            TIMEOUT_SETUP,
            &mut buffer,
            &raw mut fetched,
        )
    }
    .map_err(|e| {
        SaoError::Setup(format!(
            "the drive would not describe the disc: {} ({e})",
            sense_text(&sense)
        ))
    })?;

    if (fetched as usize) < 20 {
        return Err(SaoError::Setup(
            "the drive returned no lead-in address for this disc".to_string(),
        ));
    }

    let start = Msf { minute: buffer[17], second: buffer[18], frame: buffer[19] };
    let sectors = lead_in_sectors(start.to_sector());
    crate::app_deprintln!(
        "[burn] lead-in starts at {:02}:{:02}:{:02} ({} sectors)",
        start.minute,
        start.second,
        start.frame,
        sectors
    );
    Ok(LeadIn { start, sectors })
}

/// Write the CD-TEXT into the lead-in.
///
/// The lead-in is **not** just long enough to hold the packs once. It runs from
/// the disc's ATIP lead-in start (typically ~97 minutes, so ~13 500 sectors) up
/// to the pregap at −150, and the pack sequence is **repeated over and over**
/// to fill the whole of it. That repetition is the point: a player picks the
/// text up wherever in the lead-in it happens to start reading.
///
/// Writing only enough sectors for one pass — which the first two attempts at
/// this did — leaves a lead-in the drive has to make up the rest of, and the
/// text is not there to be read back.
fn write_cd_text_lead_in(
    ex: &IDiscRecorder2Ex,
    block: &CdTextBlock,
    lead_in: &LeadIn,
    chunk_sectors: usize,
) -> Result<(), SaoError> {
    let subchannel = block.to_subchannel();
    let source_sectors = block.sector_count();
    if source_sectors == 0 || lead_in.sectors == 0 {
        return Ok(());
    }

    let mut lba = lead_in_start_lba(lead_in.sectors);
    let mut remaining = lead_in.sectors as usize;
    // One cycling read position through the pack sectors.
    let mut cursor = 0_usize;
    let mut buffer = vec![0_u8; chunk_sectors * SUBCHANNEL_BYTES_PER_SECTOR];

    crate::app_deprintln!(
        "[burn] writing {} lead-in sectors from LBA {} ({} sectors of CD-TEXT, repeated)",
        lead_in.sectors,
        lba,
        source_sectors
    );

    while remaining > 0 {
        let sectors = remaining.min(chunk_sectors);
        for slot in 0..sectors {
            let from = cursor * SUBCHANNEL_BYTES_PER_SECTOR;
            let to = slot * SUBCHANNEL_BYTES_PER_SECTOR;
            buffer[to..to + SUBCHANNEL_BYTES_PER_SECTOR]
                .copy_from_slice(&subchannel[from..from + SUBCHANNEL_BYTES_PER_SECTOR]);
            cursor = (cursor + 1) % source_sectors;
        }

        let cdb = write_10_cdb(lba, sectors as u16);
        let payload = &buffer[..sectors * SUBCHANNEL_BYTES_PER_SECTOR];
        write_with_backoff(ex, &cdb, payload).map_err(|reason| {
            SaoError::Write(format!("writing the CD-TEXT lead-in failed: {reason}"))
        })?;

        lba += sectors as i32;
        remaining -= sectors;
    }
    Ok(())
}

/// Send one `WRITE(10)`, waiting out a full drive buffer rather than failing.
///
/// A drive that cannot take more data reports Not Ready / "long write in
/// progress" (sense `2/04/08`). That is back-pressure, not an error — the only
/// correct response is to wait and try the same block again. Treating it as a
/// failure would abort a burn mid-disc for no reason, and writing a whole
/// lead-in makes hitting it near-certain.
fn write_with_backoff(
    ex: &IDiscRecorder2Ex,
    cdb: &[u8; 10],
    payload: &[u8],
) -> Result<(), String> {
    /// Long enough to matter, short enough not to starve the drive.
    const BACKOFF: Duration = Duration::from_millis(40);
    /// ~40 seconds of continuous back-pressure before giving up.
    const MAX_RETRIES: u32 = 1000;

    for _ in 0..MAX_RETRIES {
        let mut sense = [0_u8; 18];
        // SAFETY: `payload` outlives the call; sense is written by the drive.
        let result = unsafe { ex.SendCommandSendDataToDevice(cdb, &mut sense, TIMEOUT_WRITE, payload) };
        match result {
            Ok(()) => return Ok(()),
            Err(error) => {
                let key = sense[2] & 0x0F;
                if key == 0x02 && sense[12] == 0x04 && sense[13] == 0x08 {
                    std::thread::sleep(BACKOFF);
                    continue;
                }
                return Err(format!("{} ({error})", sense_text(&sense)));
            }
        }
    }
    Err("the drive stayed busy for too long".to_string())
}

fn write_program_area(
    app: &AppHandle,
    job_id: &str,
    ex: &IDiscRecorder2Ex,
    tracks: &[RenderedTrack],
    sectors_total: u32,
    chunk_sectors: usize,
    cancel: &Arc<AtomicBool>,
) -> Result<u32, SaoError> {
    let mut source = SectorSource::open(tracks).map_err(SaoError::Write)?;
    let mut buffer = vec![0_u8; chunk_sectors * MAIN_BYTES];
    let mut lba: i32 = 0;
    let mut written: u32 = 0;
    let mut last_emit = 0_u64;

    loop {
        if cancel.load(Ordering::Relaxed) {
            // The disc is already spoiled, but stopping the laser sooner is
            // still better than burning the rest of it.
            return Err(SaoError::Write("cancelled".to_string()));
        }

        let filled = source.read(&mut buffer).map_err(SaoError::Write)?;
        if filled == 0 {
            break;
        }
        // Rendering guarantees sector alignment, so a partial sector here
        // means a truncated file rather than a normal end.
        if !filled.is_multiple_of(MAIN_BYTES) {
            return Err(SaoError::Write(
                "the rendered audio ended mid-sector; the burn cannot continue".to_string(),
            ));
        }

        let sectors = (filled / MAIN_BYTES) as u16;
        let cdb = write_10_cdb(lba, sectors);
        write_with_backoff(ex, &cdb, &buffer[..filled])
            .map_err(|reason| SaoError::Write(format!("writing audio failed: {reason}")))?;

        lba += i32::from(sectors);
        written += u32::from(sectors);

        let now = epoch_ms();
        if u128::from(now.saturating_sub(last_emit)) >= PROGRESS_THROTTLE_MS {
            last_emit = now;
            emit_progress(
                app,
                job_id,
                BurnPhase::Writing,
                None,
                written.min(sectors_total),
                sectors_total,
                None,
            );
        }
    }

    Ok(written)
}

/// Flush the drive's cache so the session is complete before we let go.
fn synchronize_cache(ex: &IDiscRecorder2Ex) -> Result<(), SaoError> {
    const OP_SYNCHRONIZE_CACHE: u8 = 0x35;
    let cdb = [OP_SYNCHRONIZE_CACHE, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    let mut sense = [0_u8; 18];
    let started = Instant::now();
    // SAFETY: a no-data command; the drive may take a while to finalise.
    let result = unsafe { ex.SendCommandNoData(&cdb, &mut sense, TIMEOUT_WRITE) };
    crate::app_deprintln!("[burn] finalise took {:?}", started.elapsed());
    result.map_err(|e| {
        SaoError::Write(format!(
            "the drive could not finalise the disc: {} ({e})",
            sense_text(&sense)
        ))
    })
}

fn epoch_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

// ── Read-back verification ───────────────────────────────────────────────────

/// Read the CD-TEXT the drive actually stored in the lead-in and say what was
/// found.
///
/// `READ TOC/PMA/ATIP` with format `0101b` returns the lead-in's CD-TEXT packs.
/// Two things this must never do: report "no CD-TEXT" when the drive simply
/// refused the query, and report success on a buffer of zeros. Only packs whose
/// CRC checks out are counted.
///
/// Note that a drive often caches the table of contents it read when the disc
/// was loaded. Immediately after a burn that cache can predate the lead-in we
/// just wrote, so a `checked: true, packs: 0` result straight after burning is
/// not proof the disc is blank — re-checking with the disc reloaded is.
pub fn verify_cd_text(recorder: &IDiscRecorder2) -> CdTextVerification {
    const OP_READ_TOC: u8 = 0x43;
    const FORMAT_CD_TEXT: u8 = 0x05;
    /// Big enough for a full block (255 packs) with room to spare, small
    /// enough that no drive balks at the allocation length.
    const BUFFER_BYTES: usize = 4 + 512 * crate::cdtext::PACK_BYTES;

    let Ok(ex) = recorder.cast::<IDiscRecorder2Ex>() else {
        return CdTextVerification::unreadable("this drive exposes no command interface");
    };

    let mut buffer = vec![0_u8; BUFFER_BYTES];
    let len = BUFFER_BYTES as u16;
    let cdb = [
        OP_READ_TOC,
        0,
        FORMAT_CD_TEXT,
        0,
        0,
        0,
        0,
        (len >> 8) as u8,
        len as u8,
        0,
    ];
    let mut sense = [0_u8; 18];
    let mut fetched: u32 = 0;

    // SAFETY: the drive writes at most `buffer.len()` bytes and reports how many.
    let read = unsafe {
        ex.SendCommandGetDataFromDevice(
            &cdb,
            &mut sense,
            TIMEOUT_SETUP,
            &mut buffer,
            &raw mut fetched,
        )
    };

    if let Err(error) = read {
        let detail = sense_text(&sense);
        crate::app_eprintln!("[burn] could not read CD-TEXT back: {detail} ({error})");
        return CdTextVerification::unreadable(format!(
            "the drive would not report the disc's CD-TEXT: {detail}"
        ));
    }

    // Header: two bytes of length (excluding themselves) then two reserved.
    let fetched = (fetched as usize).min(BUFFER_BYTES);
    if fetched <= 4 {
        crate::app_deprintln!("[burn] CD-TEXT read-back returned {fetched} bytes");
        return CdTextVerification::found(0);
    }

    let packs = crate::cdtext::count_valid_packs(&buffer[4..fetched]) as u32;
    crate::app_deprintln!("[burn] CD-TEXT read-back: {fetched} bytes, {packs} valid packs");
    CdTextVerification::found(packs)
}

