//! Session-At-Once writing on Linux, with an optional CD-TEXT lead-in.
//!
//! A direct translation of the Windows path in `win_sao.rs`, which is the one
//! that was fought out against real hardware. The three things that had to be
//! right there are the same three here, and are worth restating because none
//! of them is obvious:
//!
//! 1. The lead-in DATA FORM is `41h` — raw P-W from the host, main channel
//!    generated by the drive.
//! 2. The lead-in is **the whole lead-in**, from the disc's ATIP start (around
//!    97 minutes, so ~13 500 sectors) up to the pregap at −150, with the pack
//!    sequence repeated to fill it. Writing only enough sectors to hold the
//!    packs once produces a disc whose CD-TEXT cannot be read back.
//! 3. The cue sheet's lead-in entry carries the disc's real lead-in start,
//!    read from `READ DISC INFORMATION`, not zero.
//!
//! Unlike Windows there is no second path to fall back to, so a refusal during
//! setup is reported rather than quietly retried a different way. That makes
//! the ordering below matter: everything up to and including `SEND CUE SHEET`
//! leaves the disc untouched.

use std::fs::File;
use std::io::Read;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use tauri::AppHandle;

use super::sg::ScsiDevice;
use crate::cdtext::{CdTextBlock, CdTextInput, CdTextTrack, SUBCHANNEL_BYTES_PER_SECTOR};
use crate::job::{emit_progress, PROGRESS_THROTTLE_MS};
use crate::mmc::cue::{build_cue_sheet, CueTrack, Msf};
use crate::mmc::mode::{self, WriteParameters};
use crate::mmc::scsi;
use crate::mmc::{
    lead_in_sectors, lead_in_start_lba, read_disc_information_cdb, send_cue_sheet_cdb, write_10_cdb,
};
use crate::model::{BurnOptions, BurnPhase, BYTES_PER_AUDIO_SECTOR};
use crate::render::RenderedTrack;

/// Sectors per `WRITE(10)`. 27 × 2352 is just under 64 KB, which every drive
/// accepts and which sits inside the kernel's default SG buffer.
const CHUNK_SECTORS: usize = 27;

const TIMEOUT_SETUP: u32 = 30;
const TIMEOUT_WRITE: u32 = 300;

/// Retry budget for the lead-in, which a drive can legitimately be too busy
/// for while it settles.
const LEAD_IN_RETRIES: u32 = 24;
const LEAD_IN_BACKOFF: Duration = Duration::from_millis(40);

/// Where the lead-in starts and how long it is.
struct LeadIn {
    start: Msf,
    sectors: u32,
}

/// Build the CD-TEXT block for this disc, or `None` when it cannot be encoded.
///
/// Deliberately identical to `win::cd_text_block`: the disc title and performer
/// come from the options the user filled in, not from guessing at the first
/// track, so the same queue produces the same disc on either platform.
pub fn cd_text_block(options: &BurnOptions, tracks: &[RenderedTrack]) -> Option<CdTextBlock> {
    let input = CdTextInput {
        disc_title: options.disc_title.clone().unwrap_or_default(),
        disc_performer: options.disc_performer.clone().unwrap_or_default(),
        tracks: tracks
            .iter()
            .map(|track| CdTextTrack {
                title: track.title.clone(),
                performer: track.artist.clone(),
            })
            .collect(),
    };
    match CdTextBlock::encode(&input) {
        Ok(block) => Some(block),
        Err(error) => {
            crate::app_eprintln!("[burn] CD-TEXT not written: {error}");
            None
        }
    }
}

/// Feeds the program area 2352-byte sectors, track after track.
struct SectorSource {
    files: Vec<File>,
    current: usize,
}

impl SectorSource {
    fn open(tracks: &[RenderedTrack]) -> Result<Self, String> {
        let files = tracks
            .iter()
            .map(|track| {
                File::open(&track.path)
                    .map_err(|e| format!("cannot read {}: {e}", track.path.display()))
            })
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Self { files, current: 0 })
    }

    /// Rendering padded every track to a sector boundary, so a short read means
    /// one file ended and the next track continues the disc.
    fn read(&mut self, buffer: &mut [u8]) -> Result<usize, String> {
        let mut filled = 0;
        while filled < buffer.len() && self.current < self.files.len() {
            let read = self.files[self.current]
                .read(&mut buffer[filled..])
                .map_err(|e| format!("reading rendered audio failed: {e}"))?;
            if read == 0 {
                self.current += 1;
            } else {
                filled += read;
            }
        }
        Ok(filled)
    }
}

/// Write the whole session. Returns the program-area sectors written.
#[allow(clippy::too_many_arguments)] // One write; bundling would only move the arity.
pub fn write_session(
    app: &AppHandle,
    job_id: &str,
    device: &ScsiDevice,
    tracks: &[RenderedTrack],
    cd_text: Option<&CdTextBlock>,
    catalog: Option<&str>,
    test_write: bool,
    buffer_underrun_free: bool,
    cancel: &Arc<AtomicBool>,
) -> Result<u32, String> {
    // ── Negotiation. Nothing below writes to the disc. ───────────────────
    configure_write_parameters(device, cd_text.is_some(), test_write, buffer_underrun_free)?;

    let cue_tracks: Vec<CueTrack> = tracks
        .iter()
        .map(|track| CueTrack {
            sectors: track.sectors,
            isrc: track.isrc.clone(),
        })
        .collect();

    // The lead-in geometry has to be known before the cue sheet, which
    // announces where the lead-in starts.
    let lead_in = match cd_text {
        Some(_) => Some(read_lead_in(device)?),
        None => None,
    };
    let sheet = build_cue_sheet(&cue_tracks, lead_in.as_ref().map(|l| l.start), catalog);
    device
        .send(&send_cue_sheet_cdb(sheet.len() as u32), &sheet, TIMEOUT_SETUP)
        .map_err(|e| format!("the drive would not accept the disc layout: {e}"))?;

    if cancel.load(Ordering::Relaxed) {
        return Err("cancelled".to_string());
    }

    // ── Past this line the laser is on. ──────────────────────────────────
    let sectors_total: u32 = tracks.iter().map(|track| track.sectors).sum();

    if let (Some(block), Some(lead_in)) = (cd_text, lead_in.as_ref()) {
        write_cd_text_lead_in(device, block, lead_in)?;
    }

    let written = write_program_area(app, job_id, device, tracks, sectors_total, cancel)?;

    device
        .execute(&scsi::synchronize_cache_cdb(), TIMEOUT_WRITE)
        .map_err(|e| format!("the drive could not flush its buffer: {e}"))?;

    Ok(written)
}

/// Read the Write Parameters page, edit it, and hand it back.
fn configure_write_parameters(
    device: &ScsiDevice,
    cd_text: bool,
    test_write: bool,
    buffer_underrun_free: bool,
) -> Result<(), String> {
    let mut buffer = [0_u8; 128];
    let cdb = scsi::mode_sense_10_cdb(scsi::PAGE_WRITE_PARAMETERS, buffer.len() as u16);
    let read = device
        .receive(&cdb, &mut buffer, TIMEOUT_SETUP)
        .map_err(|e| format!("the drive would not report its write settings: {e}"))?;

    let page = scsi::mode_page_from_sense(&buffer[..read])
        .ok_or_else(|| "the drive returned no write-parameters page".to_string())?;

    let edited = mode::apply(
        page,
        WriteParameters {
            test_write,
            buffer_underrun_free,
            raw_subchannel: cd_text,
        },
    )
    .map_err(|e| format!("the drive's write settings could not be prepared: {e}"))?;

    let payload = scsi::mode_select_payload(&edited);
    device
        .send(
            &scsi::mode_select_10_cdb(payload.len() as u16),
            &payload,
            TIMEOUT_SETUP,
        )
        .map_err(|e| format!("the drive refused Session-At-Once: {e}"))
}

/// Where this disc's lead-in begins, from `READ DISC INFORMATION` bytes 17..20.
fn read_lead_in(device: &ScsiDevice) -> Result<LeadIn, String> {
    let mut buffer = [0_u8; 34];
    let read = device
        .receive(
            &read_disc_information_cdb(buffer.len() as u16),
            &mut buffer,
            TIMEOUT_SETUP,
        )
        .map_err(|e| format!("the drive would not describe the disc: {e}"))?;

    if read < 20 {
        return Err("the drive returned no lead-in address for this disc".to_string());
    }

    let start = Msf {
        minute: buffer[17],
        second: buffer[18],
        frame: buffer[19],
    };
    let sectors = lead_in_sectors(start.to_sector());
    crate::app_deprintln!(
        "[burn] lead-in starts at {:02}:{:02}:{:02} ({} sectors)",
        start.minute,
        start.second,
        start.frame,
        sectors
    );
    Ok(LeadIn { start, sectors })
}

/// Write the CD-TEXT across the entire lead-in.
///
/// The pack sequence is repeated to fill it — a lead-in holding the packs only
/// once produces a disc whose CD-TEXT no player can find.
fn write_cd_text_lead_in(
    device: &ScsiDevice,
    block: &CdTextBlock,
    lead_in: &LeadIn,
) -> Result<(), String> {
    let subchannel = block.to_subchannel();
    let source_sectors = subchannel.len() / SUBCHANNEL_BYTES_PER_SECTOR;
    if source_sectors == 0 {
        return Ok(());
    }

    let mut lba = lead_in_start_lba(lead_in.sectors);
    let mut remaining = lead_in.sectors as usize;
    let mut cursor = 0_usize;

    while remaining > 0 {
        let batch = remaining.min(CHUNK_SECTORS);
        let mut payload = Vec::with_capacity(batch * SUBCHANNEL_BYTES_PER_SECTOR);
        for _ in 0..batch {
            let at = cursor * SUBCHANNEL_BYTES_PER_SECTOR;
            payload.extend_from_slice(&subchannel[at..at + SUBCHANNEL_BYTES_PER_SECTOR]);
            cursor = (cursor + 1) % source_sectors;
        }

        write_with_backoff(device, lba, batch as u16, &payload)?;
        lba += batch as i32;
        remaining -= batch;
    }
    Ok(())
}

/// `WRITE(10)`, retrying while the drive says it is still getting ready.
///
/// Sense 2/04/08 is a drive that has not finished settling, not a failure; the
/// Windows path needed exactly this and so does this one.
fn write_with_backoff(
    device: &ScsiDevice,
    lba: i32,
    blocks: u16,
    payload: &[u8],
) -> Result<(), String> {
    let cdb = write_10_cdb(lba, blocks);
    let mut attempt = 0;
    loop {
        match device.send(&cdb, payload, TIMEOUT_WRITE) {
            Ok(()) => return Ok(()),
            Err(error) => {
                let retryable = matches!(error.sense, Some((0x02, 0x04, _)));
                if retryable && attempt < LEAD_IN_RETRIES {
                    attempt += 1;
                    std::thread::sleep(LEAD_IN_BACKOFF);
                    continue;
                }
                return Err(format!("writing the CD-TEXT lead-in failed: {error}"));
            }
        }
    }
}

/// Write the audio, reporting progress as it goes.
fn write_program_area(
    app: &AppHandle,
    job_id: &str,
    device: &ScsiDevice,
    tracks: &[RenderedTrack],
    sectors_total: u32,
    cancel: &Arc<AtomicBool>,
) -> Result<u32, String> {
    let mut source = SectorSource::open(tracks)?;
    let mut buffer = vec![0_u8; CHUNK_SECTORS * BYTES_PER_AUDIO_SECTOR];
    let mut lba: i32 = 0;
    let mut written: u32 = 0;
    let mut last_emit = Instant::now();

    emit_progress(
        app,
        job_id,
        BurnPhase::Writing,
        None,
        0,
        sectors_total,
        None,
    );

    loop {
        if cancel.load(Ordering::Relaxed) {
            return Err("cancelled".to_string());
        }

        let filled = source.read(&mut buffer)?;
        if filled == 0 {
            break;
        }
        let sectors = filled / BYTES_PER_AUDIO_SECTOR;
        if sectors == 0 {
            break;
        }

        device
            .send(
                &write_10_cdb(lba, sectors as u16),
                &buffer[..sectors * BYTES_PER_AUDIO_SECTOR],
                TIMEOUT_WRITE,
            )
            .map_err(|e| format!("writing to the disc failed: {e}"))?;

        lba += sectors as i32;
        written += sectors as u32;

        if last_emit.elapsed().as_millis() >= PROGRESS_THROTTLE_MS {
            last_emit = Instant::now();
            emit_progress(
                app,
                job_id,
                BurnPhase::Writing,
                None,
                written,
                sectors_total,
                None,
            );
        }
    }

    emit_progress(
        app,
        job_id,
        BurnPhase::Writing,
        None,
        written,
        sectors_total,
        None,
    );
    Ok(written)
}
